server:
  port: 8888
spring:
  application:
    name: config-server
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:9090}
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS