spring:
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:9090}
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    env:
      post:
        enabled: true