server:
  port: 8080
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  prefix: /api
  stripPrefix: false
  routes:
    restaurant-service:
      path: /restaurants/**
      url: http://localhost:9010
      stripPrefix: false
      serviceId: restaurant-service
    order-service:
      path: /orders/**
      url: http://localhost:9020
      stripPrefix: false
      serviceId: order-service
    review-service:
      path: /reviews/**
      url: http://localhost:9030
      stripPrefix: false
      serviceId: review-service