server:
  port: 8060
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  prefix: /api
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
    restaurant-service:
      path: /restaurants/**
      serviceId: restaurant-service
    review-service:
      path: /reviews/**
      serviceId: review-service
    customer-service:
      path: /customers/**
      serviceId: customer-service
